// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1:string,arg2:number):Promise<void>;

export function GetDownloadPath():Promise<string>;

export function GetNamespace():Promise<string>;

export function GetProxy():Promise<string>;

export function GetTDLPath():Promise<string>;

export function GetVersion():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SaveWindowSize(arg1:number,arg2:number):Promise<void>;

export function SelectDownloadDir():Promise<string>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function SelectFolderByFile():Promise<string>;

export function SelectTDLFile():Promise<string>;

export function SelectTextFile():Promise<string>;

export function SetDownloadPath(arg1:string):Promise<void>;

export function SetNamespace(arg1:string):Promise<void>;

export function SetProxy(arg1:string):Promise<void>;

export function SetTDLPath(arg1:string):Promise<void>;

export function Upload(arg1:string,arg2:string,arg3:number,arg4:boolean,arg5:boolean):Promise<void>;
