// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1, arg2) {
  return window['go']['main']['App']['Download'](arg1, arg2);
}

export function GetDownloadPath() {
  return window['go']['main']['App']['GetDownloadPath']();
}

export function GetNamespace() {
  return window['go']['main']['App']['GetNamespace']();
}

export function GetProxy() {
  return window['go']['main']['App']['GetProxy']();
}

export function GetTDLPath() {
  return window['go']['main']['App']['GetTDLPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenDownloadDir() {
  return window['go']['main']['App']['OpenDownloadDir']();
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function SaveWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SaveWindowSize'](arg1, arg2);
}

export function SelectDownloadDir() {
  return window['go']['main']['App']['SelectDownloadDir']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SelectFolderByFile() {
  return window['go']['main']['App']['SelectFolderByFile']();
}

export function SelectTDLFile() {
  return window['go']['main']['App']['SelectTDLFile']();
}

export function SelectTextFile() {
  return window['go']['main']['App']['SelectTextFile']();
}

export function SetDownloadPath(arg1) {
  return window['go']['main']['App']['SetDownloadPath'](arg1);
}

export function SetNamespace(arg1) {
  return window['go']['main']['App']['SetNamespace'](arg1);
}

export function SetProxy(arg1) {
  return window['go']['main']['App']['SetProxy'](arg1);
}

export function SetTDLPath(arg1) {
  return window['go']['main']['App']['SetTDLPath'](arg1);
}

export function Upload(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Upload'](arg1, arg2, arg3, arg4, arg5);
}
